### ISSUE TITLE
CGP - Segmentation fault (during Graph building)

### ISSUE THREAD

**Issue by fbemm** [Gaius-Augustus/Augustus#13]
Hey,

cross posting from CAT:

https://github.com/ComparativeGenomicsToolkit/Comparative-Annotation-Toolkit/issues/109

F

**Comment by MarioStanke** [comment]
Hi Felix,

I am running your example data right now and augustus produces predictions (albeit I did not let it run to the end).
I suspect that your crash is due to issue 10 that we had fixed already:
[Issue 10](https://github.com/Gaius-Augustus/Augustus/issues/10)

Please try again with the current version from GitHub.

Best, Mario

**Comment by fbemm** [comment]
Fix it! Thanks, Mario
