### ISSUE TITLE
Fatal error (randseqaccess.hh:20:21: fatal error: mysql++.h)

### ISSUE THREAD

**Issue by Tdanis** [Gaius-Augustus/Augustus#130]
Hello, I downloaded augustus 3.3.3 and after "make" in the directory , I took this error 

g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o randseqaccess.o randseqaccess.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
In file included from randseqaccess.cc:10:0:
../include/randseqaccess.hh:20:21: fatal error: mysql++.h: No such file or directory
 #include <mysql++.h>
                     ^
compilation terminated.
Makefile:61: recipe for target 'randseqaccess.o' failed
make: *** [randseqaccess.o] Error 1

Note: I have not sudo privileges

Could you help me please,?

**Comment by MarioStanke** [comment]
1) Have someone with sudo privileges install the dependencies listed on the main page, in particular libmysql++-dev.
Or
2) Comment the following line in common.mk like this  
```
#COMPGENEPRED = true
```
and recompile
``` make clean all```
This will disable comparative gene prediction (CGP).

**Comment by Tdanis** [comment]
Thank you Mario Stanke for your help

**Comment by lyy005** [comment]
Hi Mario,
I'm trying to install Augustus 3.4.0. I commented "#COMPGENEPRED = true" as you mentioned, and recompiled using "make clean all". But I still got the error. Thank you for any suggestions. 

`In file included from randseqaccess.cc:10:0:
../include/randseqaccess.hh:21:10: fatal error: mysql++.h: No such file or directory
 #include <mysql++.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:76: recipe for target 'randseqaccess.o' failed
make[1]: *** [randseqaccess.o] Error 1
make[1]: Leaving directory '/path/bin/Augustus/Augustus/src'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by hmehlan** [comment]
Since version 3.4.0 the default behaviour for the comparative gene prediction (CGP) feature (which could use a MySQL database) is changed:
**CGP is turned on unless it is _explicitly_ turned off.** 
With this you have to set 
   `   COMPGENEPRED = false `
in [common.mk](https://github.com/Gaius-Augustus/Augustus/blob/master/common.mk#L14) . 
This behavior is described in [common.mk](https://github.com/Gaius-Augustus/Augustus/blob/master/common.mk#L10) and [README.md](https://github.com/Gaius-Augustus/Augustus/blob/master/README.md#install-dependencies).
Explicitly turning off CGP also turns off the use of the MySQL library (unless MySQL is explicitly declared as necessary).

Alternatively, you have the option to exclude only the use of the MySQL library. 
You can do this by setting 
`MYSQL = false`
in common.mk. 
This is also described in [README.md](https://github.com/Gaius-Augustus/Augustus/blob/master/README.md#install-dependencies).

Recompile with
``` make clean all```

**Comment by wmorgan485** [comment]
Thanks for the pointer to the common.mk file and the "make clean all" command. However, I couldn't find any mention of these particular problems and solutions in the linked README.md file.

**Comment by hmehlan** [comment]
To keep the [README.md](README.md) clear and lean, the installation instructions have been moved to [docs/INSTALL.md](docs/INSTALL.md#install-dependencies). 
This change has been adapted in the previous comments of this issue. 
Thank you for your comment.

**Comment by rLannes** [comment]
IF anyone has this issue, I found a fix that doesn't require sudo: 

YOU should first check that the library is truly not installed in your system.

Step one download "mysql++" from "https://tangentsoft.com" or another source you trust
untar and cd inside the mysql++ folder
run: 
./configure --prefix=$HOME/.local
make -j$(nproc)
make install

go back to augustus folded and modify the common.mk file:
uncomment :the line that start with  INCLUDE_PATH_MYSQL and LIBRARY_PATH_MYSQL
add the following line:
INCLUDE_PATH_MYSQL       := -I/usr/include -I/usr/include/mysql  -I/home/<user>/.local/include/mysql++/    # the path to mysql++ may have to be adjusted
INCLUDE_PATH_MYSQL += -I/home/<user>.local/include/mysql++/ -I/home/<user>/.local/include/
LIBRARY_PATH_MYSQL       := -L/usr/lib -L/usr/lib/x86_64-linux-gnu  -Wl,-rpath,/usr/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu
LIBRARY_PATH_MYSQL += -L/home/<user>/.local/lib/  -Wl,-rpath,/home/<user>/.local/lib

run:
make clean
make

 
Rince and repeat for any missing library.
