### ISSUE TITLE
During make, undefined reference to mysqlpp

### ISSUE THREAD

**Issue by chrisreidy** [Gaius-Augustus/Augustus#156]
Using centos7 and gcc8.3 I get about a dozen lines similar to:
randseqaccess.o: In function `mysqlpp::Query::str[abi:cxx11]()':
/usr/include/mysql++/query.h:278: undefined reference to `mysqlpp::Query::str[abi:cxx11](mysqlpp::SQLQueryParms&)'
And then it fails.  Unlike other issues with mysqlpp, make finds it where expected in /usr/include/mysql++, it just fails while using it.
mysql++-devel-3.1.0-12.el7.x86_64
mysql++-3.1.0-12.el7.x86_64

I also tried using gcc 7.3 and I tried  building augustus 3.2.3

Thanks

**Comment by hmehlan** [comment]
These linker error is caused by the new [Application Binary Interface (ABI)](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) library introduced with gcc 5.1. 
Libraries compiled with gcc > 5 are not compatible with those compiled with gcc < 5, due to changes in std::string (amongst [others](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html#manual.intro.using.abi.trouble)). 
mysql++-devel-3.1.0-12.el7.x86_64 was build with the old ABI, but the Augustus code compiled with gcc versions (8.3 and 7.3) is using the new one, leading to the conflict when trying to link them.

Your options:
- use the standard gcc 4.8.5 provided by centos 7
- if you don't want to load data through a MySQL database add 
MYSQL=false 
to file common.mk
- if you don't need comparative augustus (which annotates multiple genomes simultaenously and only for this feature the MySQL library is used) change 
COMPGENEPRED=false 
in file common.mk
- compile the Augustus code with gcc > 5 but use the old ABI by setting the macro _GLIBCXX_USE_CXX11_ABI to 0 (add 
CPPFLAGS+=-D_GLIBCXX_USE_CXX11_ABI=0 
on top of every Makefile which use libraries with the old ABI) - so both Augustus and MySQL use the old ABI.  However this approach may fail if you have to link other libraries which use the new ABI.
- rebuild the mysql libraries with gcc > 5 - so both Augustus and MySQL use the new ABI

Here is the Dockerfile [Dockerfile_centos_7.txt](https://github.com/Gaius-Augustus/Augustus/files/4813894/Dockerfile_centos_7.txt) used to reproduce this error. This is just the centos 7 version of the Dockerfile for Ubuntu we [provide](https://github.com/Gaius-Augustus/Augustus/blob/master/Dockerfile). 
In Dockerfile_centos_7.txt gcc4.8.5 is installed. 
The steps to install gcc7.3 and to reproduce the error are NOT included.

**Comment by chrisreidy** [comment]
Thank you for the detailed response.  I tried option 1 but I had built bamtools with gcc8.3. So I ended up with option 2, and excluded bam2wig since it had its own dependency tree. 
As a suggestion, it would help not to hard code the install path in the Makefile.
Thanks again
