### ISSUE TITLE
joingenes removes "gene" entries from CGP predictions

### ISSUE THREAD

**Issue by jguhlin** [Gaius-Augustus/Augustus#31]
Currently following the AUGUSTUS-CGP tutorial will lead to running the joingenes binary. This creates a file of all predictions joined into a single file, but only has transcript / CDS entries. Running gtf2gff with options -gff3 will result in a file containing mRNA, CDS, and exons, but not gene entries (although mRNA entries will have a parent, said parent by ID will not be found).

Not sure if a bug or part of the pipeline, but there should be a way to add it back in I would imagine.

**Comment by KatharinaHoff** [comment]
The problem of missing gene entries causes problems on different levels.

I have written a small Perl script for postprocessing the joingenes output, it is in Augustus/scripts at https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/fix_joingenes_gtf.pl

`fix_joingenes_gtf.pl < joingenes.gtf > joingenes.fixed.gtf`

After this, the fixed joingenes output will contain the gene feature line and correctly formatted transcript line that is fully comptabile with gtf2gff.pl:

`gtf2gff.pl < joingenes.fixed.gtf --gff3 --out=joingenes.gff3`

This issue remains open because eventually it should be fixed on joingenes level.

**Comment by Neato-Nick** [comment]
I landed here after Google brought me to https://github.com/Gaius-Augustus/Augustus/issues/39.

Looks like There hasn't been a new Augustus release since this issue was first opened. But @KatharinaHoff, your perl script did the trick and I've got a nice gff3 in hand now. Thanks!
