### ISSUE TITLE
gtf2gff.pl: transcript jg1.t1 has conflicting gene parents: and jg1

### ISSUE THREAD

**Issue by peterthorpe5** [Gaius-Augustus/Augustus#39]
Dear AUGUSTUS,

As you know Augustus is used in Braker. I am/ and several others are having issues with gft2gff.pl script. (https://github.com/Gaius-Augustus/BRAKER/issues/9) .. Braker calls it as follows: 

cat /home/pjt6/Desktop/newton_final/prot_no_utr/augustus.hints.gtf | perl -ne 'if(m/\tAUGUSTUS\t/) {print $_;}' | perl /home/pjt6/programs/Augustus/scripts/gtf2gff.pl --gff3 --out=/home/pjt6/Desktop/newton_final/prot_no_utr/augustus.hints.gff3

ERROR:
transcript jg1.t1 has conflicting gene parents: and jg1. Remember: In GTF txids need to be overall unique. at /home/pjt6/programs/Augustus/scripts/gtf2gff.pl line 120, <STDIN> line 218372.

It would be amazing if this could be solved. Will you please help?

cheers,

Pete

**Comment by KatharinaHoff** [comment]
Hi Peter
we already have an open issue for this problem at https://github.com/Gaius-Augustus/Augustus/issues/31
The core developer of joingenes has left our team a while ago. It might therefore be a while before this problem is solved on the joingenes code level.
I am closing this issue because it is a duplicate.
Best,
Katharina

**Comment by peterthorpe5** [comment]
Ok thank you for your reply Katherine.

Cheers,

Pete
