### ISSUE TITLE
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence

### ISSUE THREAD

**Issue by yveuno** [Gaius-Augustus/Augustus#40]
when I run this command 

etraining --species=generic --stopCodonExcludedFromCDS=true genes.raw.gb 2>train1.err

I get this error message.
Encountered error after reading 5941 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 5942 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 6918 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 6935 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 990 annotations.
GBProcessor::getGeneList(): Stop codon out of sequence bounds. Ignoring sequence.
Encountered error after reading 991 annotations.

**Comment by KatharinaHoff** [comment]
This means that you have sequence entries in the genbank file that don't have a stop codon at the expected position (which is the end of the terminal exon). This may for example happen if a training gene is located at the boundary of a sequence, i.e. is incomplete.

The --stopCodonExcludedFromCDS=true should reflect how you annotated your stop codon. If it is inside the boundaries of the terminal CDS feature, then it should be set to false, otherwise, it should be set to true. But I strongly assume that above error does not occur with all genes, but only with a few (as posted).

If you don't want to see the error, you can delete the entries that cause problems from the genbank file.
