### ISSUE TITLE
Unable to locate command line parameters file

### ISSUE THREAD

**Issue by katieemelianova** [Gaius-Augustus/Augustus#412]
Hi there,

I am running Augustus within MAKER and am running into an issue, perhaps you can help.

I am running maker as follows, setting the environment variables show:
```
export LIBDIR=/lisc/app/repeatmasker/4.1.6-3.12.4-5.40.0/Libraries/
export REPEATMASKER_LIB_DIR=/lisc/app/repeatmasker/4.1.6-3.12.4-5.40.0/Libraries/
export AUGUSTUS_CONFIG_PATH=/lisc/scratch/botany/katie/annotation/local_augustus_config/config
mpiexec -n 32  /lisc/app/conda/miniconda3/envs/maker-3.01.03/bin/maker -cpus 32 -base round2 maker_opts_round2.ctl maker_bopts.ctl maker_exe.ctl
```

The AUGUSTUS_CONFIG_PATH seems to contain all the folders that I need:
```
ls /lisc/scratch/botany/katie/annotation/local_augustus_config/config
cgp  extrinsic  model  parameters  profile  species
```

But when I run maker via slurm, not all the folders from the config seem to be copied across to the temporary slurm directory:

```
ls /lisc/slurm/node-d13/tmp/slurm-1874997/maker_Z8t_BU/augustus_config/19f87e9215aab674891f3238099dc663/
extrinsic  model  profile  species
```

Resulting in an error from Augustus during MAKER:
```
/lisc/app/conda/miniconda3/envs/augustus-3.5.0/bin/augustus: ERROR
Could not locate command line parameters file: /tmp/slurm-1874997/maker_Z8t_BU/augustus_config/19f87e9215aab674891f3238099dc663/parameters/aug_cmdln_parameters.json.
```

I'm not sure if this is a Augustus problem or a slurm problem - could you recommend any way to debug or suggest what could be happening?

Thanks in advance for your help :)

Best,

Katie

**Comment by MarioStanke** [comment]
It is not a slurm problem. A couple of years ago we have introduced 
`config/parameters/aug_cmdln_parameters.json`
so [pygustus](https://github.com/Gaius-Augustus/pygustus) can use the same command line parameters as `augustus` in C++.

I suspect that MAKER copies some directories explicitly where it should probably copy all config subdirectories except irrelevant parts of `species` (to save space). Or one could add the `parameters` subdirectory to the list of paths to copy.

If that is true it should be fixed in MAKER, but I am not sure whether it is still maintained.

**Comment by katieemelianova** [comment]
Hi Mario,

Thanks a lot for the explanation - it doesn't look like maker is under active development unfortunately. 

Best,

Katie

**Comment by rongrongy** [comment]
Hi, guys
I had the same problem as you, may I ask if you have solved it by now.
