### ISSUE TITLE
bamToWig.py tries to download and use programs during its run

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/Augustus#95]
The script `bamToWig.py` tries to download and (apparently) run programs during its execution.  This is bad, as it interferes with the reproducibility of Augustus runs.  That is, the results may differ depending on exactly what happens to be present on the download site, and/or whether the site happens to be available or not.

It would be far preferable to put these programs in the list of dependencies, as with the others.

**Comment by michaelkarlcoleman** [comment]
Hmm.  This is within a `braker.pl` run.   The thought would be that these programs (e.g., `twoBitInfo`) must be doing something that would ultimately contribute to the results of the braker run.  If the behavior of the programs on the web site change in any way over time, the ultimate results may change, and it would be quite difficult to determine why.

Beyond that, it makes debugging `braker.pl` harder as well.  Programmatically downloading and running a program seems like highly unusual and surprising behavior.

**Comment by KatharinaHoff** [comment]
The braker.pl run will die if you switch on --UTR=on and these tools are not present and cannot be downloaded.

Automatically downloaded the missing tools is supposed to make the life of our users easier... we were very hesitant to replace bam2wig by bamToWig.py because it adds even more dependencies than we had, before. So our compromise was to add it (because it's more stable), but to automatically download the dependencies if missing.

I added a note to the AUGUSTUS Readme : https://github.com/Gaius-Augustus/Augustus/commit/0b0f1244daeb2cb0be422cedc5956d8ad883b8cb

**Comment by michaelkarlcoleman** [comment]
Thanks. --Mike
